ACCEL_ASCII ""

(asciiHeader
  (asciiVersion 3 0)
  (timeStamp 2026 8 20 1 15 18)
  (program "Protel DXP" "Version 1.0.0.30000")
  (copyright "Copyright © Altium Limited 2015")
  (fileAuthor "")
  (headerString "")
  (fileUnits mil)
  (guidString "{00000000-0000-0000-0000-000000000000}")
)
(library "Library_1"
  (textStyleDef "(Default)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 91.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PartStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(WireStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PortStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "10pTIMESNEWROMAN"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (symbolDef "ch342f_1_N"
    (originalName "ch342f_1_N")
    (pin (pinNum 1)  (pt -600 250) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 250) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 250) "RI0" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt -600 150) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 150) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 150) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt -600 50) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 50) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 50) "UD+" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt -600 -50) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 -50) "4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 -50) "UD-" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt -600 -150) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 -150) "5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 -150) "VIO" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt -600 -250) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -650 -250) "6" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 -250) "V3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt -250 -600) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -250 -650) "7" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -250 -600) "VDD5" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt -150 -600) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -650) "8" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -150 -600) "VBUS" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt -50 -600) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -50 -650) "9" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -50 -600) "RST" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt 50 -600) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 50 -650) "10" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 50 -600) "CTS1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt 150 -600) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -650) "11" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 150 -600) "RTS1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt 250 -600) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 250 -650) "12" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 250 -600) "RXD1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 13)  (pt 600 -250) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -250) "13" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 -250) "TXD1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 14)  (pt 600 -150) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -150) "14" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 -150) "DSR1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 15)  (pt 600 -50) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -50) "15" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 -50) "DTR1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 16)  (pt 600 50) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 50) "16" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 50) "DCD1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 17)  (pt 600 150) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 150) "17" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 150) "RI1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 18)  (pt 600 250) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 250) "18" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 250) "CTS0" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 19)  (pt 250 600) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 250 650) "19" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 250 600) "RTS0" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 20)  (pt 150 600) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 650) "20" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 150 600) "RXD0" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 21)  (pt 50 600) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 50 650) "21" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 50 600) "TXD0" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 22)  (pt -50 600) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -50 650) "22" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -50 600) "DSR0" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 23)  (pt -150 600) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 650) "23" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -150 600) "DTR0" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 24)  (pt -250 600) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -250 650) "24" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -250 600) "DCD0" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 25)  (pt 600 -500) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 650 -500) "25" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 -500) "EP" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -600 -600) (pt -600 600) (width 10) )
    (line (pt -600 -600) (pt 600 -600) (width 10) )
    (line (pt -600 600) (pt 600 600) (width 10) )
    (line (pt 600 600) (pt 600 -600) (width 10) )
    (arc (pt -550 550) (radius 15) (startAngle 0) (sweepAngle 360) (width 10))
    (attr "RefDes" ""  (pt 720 520) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -720 720) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Symbol" "CH342F"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "LCSC Part Name" "USB??????"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "SupplierPart" "C2841530"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Manufacturer" "WCH(????)"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ManufacturerPart" "CH342F"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Supplier Footprint" "QFN-24-EP(4x4)"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "JLCPCB Part Class" "Extended Part"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Datasheet" "https://item.szlcsc.com/datasheet/CH342F/3023645.html"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Supplier" "LCSC"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "AddInBom" "yes"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ConvertToPcb" "yes"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "FootprintName" "VQFN-24_L4.0-W4.0-P0.50-TL-EP2.4"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ModelId" "670c3f6fdaab4b54ab3eb2c6630906c7"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ModelName" "VQFN-24_L4.0-W4.0-H1.0-P0.50"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ModelTransform" "158.267,158.267,0,0,0,0,0,0,0"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Applications Funct83" "USB to serial"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "USB Protocol" "USB 2.0"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Number of Channels" "2"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Voltage - Supply" "3.3V;5V"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Data Rate" "3Mbps"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Operating Temperat27" "-40?~+85?"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Current - Supply" "15mA"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Quiescent Supply C2F" "160uA"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Features" "Programmable baud rate;Wake-up function;Built-in clock generator;Hardware flow control support;Low-power mode;Power-on reset"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (compDef "CH342F"
    (originalName "CH342F")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "ch342f_1_N") )
    (attachedPattern (patternNum 1) (patternName "VQFN-24_L4.0-W4.0-P0.50-TL-E22")
      (numPads 0)
      (padPinMap
      )
    )
  )
)

(netlist "Netlist_1"
)

(schematicDesign "SchDesign_1"
  (schDesignHeader
    (workspaceSize 11500 7600)
    (gridDfns
      (grid "100mil")
    )
    (designInfo
      (fieldSet "(Default)"
        (fieldDef "Time" "")
        (fieldDef "Date" "")
        (fieldDef "Approved By" "")
        (fieldDef "Checked By" "")
        (fieldDef "Author" "")
        (fieldDef "Company Name" "")
        (fieldDef "Drawn By" "")
        (fieldDef "Engineer" "")
        (fieldDef "Organization" "")
        (fieldDef "Address1" "")
        (fieldDef "Address2" "")
        (fieldDef "Address3" "")
        (fieldDef "Address4" "")
        (fieldDef "Title" "")
        (fieldDef "Drawing Number" "")
        (fieldDef "Revision" "")
        (fieldDef "Rule" "")
        (fieldDef "ImagePath" "")
        (fieldDef "ProjectName" "")
        (fieldDef "Application_BuildNumber" "")
      )
    )
    (refPointSize 100)
    (infoPointSize 100)
    (junctionSize 20)
    (refPointSizePrint 100)
    (infoPointSizePrint 100)
    (junctionSizePrint 20)
  )

  (sheet "Sheet1" (sheetNum 1)
    (titleSheet ""
      1.0000
      (isVisible True)
      (offset 0.0 0.0)
      (border
        (isVisible True)
        (height 7600)
        (width 11500)
        (offset 0 0)
      )
      (zones
        (isVisible True)
        (textStyleRef "(Default)")
        (horizontalZones 4
          (numDirection ascending)
          (numType Alphabetic)
        )
        (verticalZones 4
          (numDirection ascending)
          (numType Numeric)
        )
      )
    )
    (fieldSetRef "(Default)")
  )
  (sheet "CH342F" (sheetNum 2)
    (titleSheet ""
      1.0000
      (isVisible True)
      (offset 0.0 0.0)
      (border
        (isVisible False)
        (height 4000)
        (width 5000)
        (offset 0 0)
      )
      (zones
        (isVisible True)
        (textStyleRef "(Default)")
        (horizontalZones 0
          (numDirection ascending)
          (numType Alphabetic)
        )
        (verticalZones 0
          (numDirection ascending)
          (numType Numeric)
        )
      )
    )
    (fieldSetRef "(Default)")
    (symbol (symbolRef "ch342f_1_N") (refDesRef "U?") (partNum 1) (pt 2500 2000)
      (attr "RefDes" "U?" (pt 720 520) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Symbol" "CH342F" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "LCSC Part Name" "USB??????" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SupplierPart" "C2841530" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer" "WCH(????)" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ManufacturerPart" "CH342F" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supplier Footprint" "QFN-24-EP(4x4)" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "JLCPCB Part Class" "Extended Part" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Datasheet" "https://item.szlcsc.com/datasheet/CH342F/3023645.html" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supplier" "LCSC" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "AddInBom" "yes" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ConvertToPcb" "yes" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "FootprintName" "VQFN-24_L4.0-W4.0-P0.50-TL-EP2.4" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ModelId" "670c3f6fdaab4b54ab3eb2c6630906c7" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ModelName" "VQFN-24_L4.0-W4.0-H1.0-P0.50" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ModelTransform" "158.267,158.267,0,0,0,0,0,0,0" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Applications Funct83" "USB to serial" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "USB Protocol" "USB 2.0" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Number of Channels" "2" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Voltage - Supply" "3.3V;5V" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Data Rate" "3Mbps" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Operating Temperat27" "-40?~+85?" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Current - Supply" "15mA" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Quiescent Supply C2F" "160uA" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Features" "Programmable baud rate;Wake-up function;Built-in clock generator;Hardware flow control support;Low-power mode;Power-on reset" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "ch342f" (pt -720 720) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
  )
  (sheet "CH342F" (sheetNum 3)
    (titleSheet ""
      1.0000
      (isVisible True)
      (offset 0.0 0.0)
      (border
        (isVisible False)
        (height 4000)
        (width 5000)
        (offset 0 0)
      )
      (zones
        (isVisible True)
        (textStyleRef "(Default)")
        (horizontalZones 0
          (numDirection ascending)
          (numType Alphabetic)
        )
        (verticalZones 0
          (numDirection ascending)
          (numType Numeric)
        )
      )
    )
    (fieldSetRef "(Default)")
    (symbol (symbolRef "ch342f_1_N") (refDesRef "U?") (partNum 1) (pt 2500 2000)
      (attr "RefDes" "U?" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Symbol" "CH342F" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "LCSC Part Name" "USB??????" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SupplierPart" "C2841530" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer" "WCH(????)" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ManufacturerPart" "CH342F" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supplier Footprint" "QFN-24-EP(4x4)" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "JLCPCB Part Class" "Extended Part" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Datasheet" "https://item.szlcsc.com/datasheet/CH342F/3023645.html" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supplier" "LCSC" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "AddInBom" "yes" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ConvertToPcb" "yes" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "FootprintName" "VQFN-24_L4.0-W4.0-P0.50-TL-EP2.4" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ModelId" "670c3f6fdaab4b54ab3eb2c6630906c7" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ModelName" "VQFN-24_L4.0-W4.0-H1.0-P0.50" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ModelTransform" "158.267,158.267,0,0,0,0,0,0,0" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Applications Funct83" "USB to serial" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "USB Protocol" "USB 2.0" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Number of Channels" "2" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Voltage - Supply" "3.3V;5V" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Data Rate" "3Mbps" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Operating Temperat27" "-40?~+85?" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Current - Supply" "15mA" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Quiescent Supply C2F" "160uA" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Features" "Programmable baud rate;Wake-up function;Built-in clock generator;Hardware flow control support;Low-power mode;Power-on reset" (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "ch342f" (pt -50 -150) (justify UpperLeft) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
  )
  (schematicPrintSettings
    (sheetList
      (sheetRef 2)
      (sheetRef 3)
      (sheetRef 4)
    )
  )
  (programState
    (gridState
      (currentAbsGrid "100mil")
      (currentRelGrid "100mil")
      (isAbsoluteGrid True)
      (isDottedGrid True)
      (isVisibleGrid True)
      (isPromptForRel False)
    )
    (ecoState (ecoRecording False))
    (currentTextStyle "(Default)")
  )
)
